package com.alsaril.codegen.classfile

import com.alsaril.codegen.ByteClassLoader
import com.alsaril.codegen.bytesOf
import com.alsaril.codegen.classfile.ClassFileBuilder.Companion.classFile
import com.alsaril.codegen.classfile.MethodAccessFlag.PUBLIC
import com.alsaril.codegen.classfile.MethodAccessFlag.STATIC
import com.alsaril.codegen.classfile.code.aload
import com.alsaril.codegen.classfile.code.athrow
import com.alsaril.codegen.classfile.code.clazz
import com.alsaril.codegen.classfile.code.construct
import com.alsaril.codegen.classfile.code.frameSame
import com.alsaril.codegen.classfile.code.iadd
import com.alsaril.codegen.classfile.code.iconst
import com.alsaril.codegen.classfile.code.ifeq
import com.alsaril.codegen.classfile.code.iload
import com.alsaril.codegen.classfile.code.ireturn
import com.alsaril.codegen.classfile.code.invokespecial
import com.alsaril.codegen.classfile.code.method
import com.alsaril.codegen.classfile.code.parent
import com.alsaril.codegen.classfile.code.`return`
import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatExceptionOfType
import org.assertj.core.api.Assertions.assertThatNoException
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test
import java.util.function.IntUnaryOperator

class ClassFileBuilderTest {

    private fun ClassFileBuilder.withConstructor() = method(
        "<init>",
        "()V",
        maxStack = 1,
        maxLocals = 1,
        PUBLIC,
    ) {
        aload(0)
        invokespecial(method(parent(), "<init>", "()V"))
        `return`()
    }

    @Nested
    inner class Assembly {

        @Test
        fun `returns the class name alongside the bytes`() {
            // when
            val (name, bytes) = classFile("Empty", "java/lang/Object").build()

            // then
            assertThat(name).isEqualTo("Empty")
            assertThat(bytes).isNotEmpty()
        }

        @Test
        fun `starts with the magic number and the java 8 version`() {
            // when
            val (_, bytes) = classFile("Header", "java/lang/Object").build()

            // then
            assertThat(bytes).startsWith(*bytesOf(0xCA, 0xFE, 0xBA, 0xBE, 0x00, 0x00, 0x00, 0x34))
        }

        @Test
        fun `ends with an empty class attribute list`() {
            // when
            val (_, bytes) = classFile("Tail", "java/lang/Object").build()

            // then
            assertThat(bytes).endsWith(*bytesOf(0x00, 0x00))
        }

        @Test
        fun `accepts a method declared without access flags`() {
            // a package private method folds to no flags at all
            assertThatNoException().isThrownBy {
                classFile("NoFlags", "java/lang/Object")
                    .method("f", "()V", maxStack = 0, maxLocals = 0) { `return`() }
                    .build()
            }
        }

        @Test
        fun `accepts several flags on one method`() {
            assertThatNoException().isThrownBy {
                classFile("ManyFlags", "java/lang/Object")
                    .method("f", "()V", maxStack = 0, maxLocals = 0, PUBLIC, STATIC) { `return`() }
                    .build()
            }
        }

        @Test
        fun `grows the output as methods are added`() {
            // given
            val bare = classFile("Bare", "java/lang/Object").build().second
            val withMethod = classFile("WithMethod", "java/lang/Object")
                .method("f", "()V", maxStack = 0, maxLocals = 0, PUBLIC) { `return`() }
                .build().second

            // then
            assertThat(withMethod.size).isGreaterThan(bare.size)
        }
    }

    /**
     * These load the generated bytes, so the JVM verifier checks the constant pool,
     * the bytecode and the stack map frames before anything runs.
     */
    @Nested
    inner class Loading {

        @Test
        fun `builds a class the jvm accepts as a Runnable`() {
            // given
            val (name, bytes) = classFile("GenRunnable", "java/lang/Object")
                .iface("java/lang/Runnable")
                .withConstructor()
                .method("run", "()V", maxStack = 0, maxLocals = 1, PUBLIC) { `return`() }
                .build()

            // when
            val instance = ByteClassLoader.loadClass(name, bytes).getDeclaredConstructor().newInstance()

            // then
            assertThat(instance).isInstanceOf(Runnable::class.java)
            assertThatNoException().isThrownBy { (instance as Runnable).run() }
        }

        @Test
        fun `returns a computed value from a static method`() {
            // given
            val (name, bytes) = classFile("GenStatic", "java/lang/Object")
                .method("f", "()I", maxStack = 2, maxLocals = 0, PUBLIC, STATIC) {
                    iconst(2)
                    iconst(3)
                    iadd()
                    ireturn()
                }
                .build()

            // when
            val result = ByteClassLoader.loadClass(name, bytes).getDeclaredMethod("f").invoke(null)

            // then
            assertThat(result).isEqualTo(5)
        }

        @Test
        fun `reads an argument out of a local slot`() {
            // given
            val (name, bytes) = classFile("GenTwice", "java/lang/Object")
                .method("twice", "(I)I", maxStack = 2, maxLocals = 1, PUBLIC, STATIC) {
                    iload(0)
                    iload(0)
                    iadd()
                    ireturn()
                }
                .build()

            // when
            val method = ByteClassLoader.loadClass(name, bytes)
                .getDeclaredMethod("twice", Int::class.javaPrimitiveType)

            // then
            assertThat(method.invoke(null, 21)).isEqualTo(42)
            assertThat(method.invoke(null, -3)).isEqualTo(-6)
        }

        @Test
        fun `compiles a function instance that adds 42 to its argument`() {
            // given a class implementing IntUnaryOperator, so slot 0 is this and slot 1 the argument
            val (name, bytes) = classFile("GenAdder", "java/lang/Object")
                .iface("java/util/function/IntUnaryOperator")
                .withConstructor()
                .method("applyAsInt", "(I)I", maxStack = 2, maxLocals = 2, PUBLIC) {
                    iload(1)
                    iconst(42)
                    iadd()
                    ireturn()
                }
                .build()

            // then the body compiles to iload_1, bipush 42, iadd, ireturn
            assertThat(bytes).containsSequence(*bytesOf(0x1B, 0x10, 0x2A, 0x60, 0xAC))

            // and the loaded class behaves like the function it describes
            val function = ByteClassLoader.loadClass(name, bytes)
                .getDeclaredConstructor().newInstance() as IntUnaryOperator

            assertThat(function.applyAsInt(0)).isEqualTo(42)
            assertThat(function.applyAsInt(1)).isEqualTo(43)
            assertThat(function.applyAsInt(-42)).isEqualTo(0)
            // int arithmetic wraps rather than widening
            assertThat(function.applyAsInt(Int.MAX_VALUE)).isEqualTo(Int.MIN_VALUE + 41)
        }

        @Test
        fun `runs a body that constructs and throws`() {
            // given
            val (name, bytes) = classFile("GenThrows", "java/lang/Object")
                .iface("java/lang/Runnable")
                .withConstructor()
                .method("run", "()V", maxStack = 2, maxLocals = 1, PUBLIC) {
                    construct(clazz("java/lang/IllegalStateException"), "<init>", "()V")
                    athrow()
                }
                .build()
            val instance = ByteClassLoader.loadClass(name, bytes).getDeclaredConstructor()
                .newInstance() as Runnable

            // then
            assertThatExceptionOfType(IllegalStateException::class.java).isThrownBy { instance.run() }
        }

        @Test
        fun `runs a body whose branch target carries a stack map frame`() {
            // given a body that jumps over the throw, so taking the branch returns normally
            val (name, bytes) = classFile("GenBranch", "java/lang/Object")
                .iface("java/lang/Runnable")
                .withConstructor()
                .method("run", "()V", maxStack = 2, maxLocals = 1, PUBLIC) {
                    iconst(0)
                    val jump = ifeq()

                    construct(clazz("java/lang/IllegalStateException"), "<init>", "()V")
                    athrow()

                    jump(loc())
                    frameSame()
                    `return`()
                }
                .build()
            val instance = ByteClassLoader.loadClass(name, bytes).getDeclaredConstructor()
                .newInstance() as Runnable

            // then
            assertThatNoException().isThrownBy { instance.run() }
        }
    }
}
